"""
Report Agent - Generates structured Markdown discovery reports and persists them
to Azure Blob Storage (reports container).

The agent consolidates the conversation history from a completed discovery
session into a well-structured report covering:
  - Executive summary
  - Business requirements captured
  - Recommended Azure architecture
  - Service breakdown with rationale
  - Next steps
"""
import logging
from typing import Any

from openai import AsyncAzureOpenAI

from app.agents.base import BaseAgent
from app.core.config import settings

logger = logging.getLogger(__name__)

_REPORT_SYSTEM_PROMPT = """
You are an Azure Solutions Architect writing a discovery report after completing
a structured architecture discovery session with a client.

Given the full conversation transcript, produce a professional Markdown report
with the following sections:

# Azure Architecture Discovery Report

## Executive Summary
Two to three sentences summarising the client's business context and the recommended approach.

## Business Requirements
Bullet list of key requirements captured during the discovery session.

## Recommended Azure Architecture
Paragraph describing the recommended architecture and why it fits the client's needs.

## Azure Services Breakdown
A table with columns: Service | Purpose | SKU/Tier | Estimated Monthly Cost.
Use real Azure service names and realistic SKU choices.

## Security & Compliance Considerations
Bullet list of security and compliance items relevant to the client.

## Next Steps
Numbered list of concrete actions the client should take to begin the deployment.

---
*Report generated by Azure Discovery Orchestrator — Powered by Azure AI*
""".strip()


class ReportAgent(BaseAgent):
    """
    Consolidates the discovery conversation into a structured Markdown report,
    then uploads it to the Azure Blob Storage reports container.
    """

    name = "report"

    def __init__(self) -> None:
        if settings.AZURE_OPENAI_KEY:
            self._client = AsyncAzureOpenAI(
                azure_endpoint=settings.AZURE_OPENAI_ENDPOINT,
                api_key=settings.AZURE_OPENAI_KEY,
                api_version=settings.AZURE_OPENAI_API_VERSION,
            )
        else:
            from azure.identity import ManagedIdentityCredential, get_bearer_token_provider
            token_provider = get_bearer_token_provider(
                ManagedIdentityCredential(),
                "https://cognitiveservices.azure.com/.default",
            )
            self._client = AsyncAzureOpenAI(
                azure_endpoint=settings.AZURE_OPENAI_ENDPOINT,
                azure_ad_token_provider=token_provider,
                api_version=settings.AZURE_OPENAI_API_VERSION,
            )

    async def run(self, user_input: str, context: dict[str, Any] | None = None) -> str:
        """
        Generate a Markdown report from the conversation transcript.

        Args:
            user_input:  The full conversation transcript as a single string,
                         or a JSON-serialised list of {role, content} messages.
            context:     Optional dict; use context["session_id"] to name the blob.

        Returns:
            The full Markdown report text.
        """
        session_id = (context or {}).get("session_id", "unknown")

        messages = [
            {"role": "system", "content": _REPORT_SYSTEM_PROMPT},
            {
                "role": "user",
                "content": (
                    f"Below is the full discovery conversation transcript.\n\n"
                    f"Session ID: {session_id}\n\n"
                    f"{user_input}\n\n"
                    "Please generate the discovery report now."
                ),
            },
        ]

        response = await self._client.chat.completions.create(
            model=settings.AZURE_OPENAI_DEPLOYMENT,
            messages=messages,
            temperature=0.3,
            max_tokens=2000,
        )

        report_md = (response.choices[0].message.content or "").strip()
        logger.info("[ReportAgent] Generated report for session %s (%d chars)", session_id, len(report_md))

        # Persist to Blob Storage if configured
        if settings.STORAGE_CONNECTION_STRING:
            await self._upload_to_blob(session_id, report_md)

        return report_md

    async def _upload_to_blob(self, session_id: str, content: str) -> None:
        """Upload the Markdown report to the reports Blob container."""
        try:
            from azure.storage.blob.aio import BlobServiceClient

            blob_name = f"{session_id}/report.md"
            async with BlobServiceClient.from_connection_string(
                settings.STORAGE_CONNECTION_STRING
            ) as blob_svc:
                container = blob_svc.get_container_client(settings.STORAGE_REPORTS_CONTAINER)
                await container.upload_blob(
                    name=blob_name,
                    data=content.encode("utf-8"),
                    overwrite=True,
                    content_settings={"content_type": "text/markdown; charset=utf-8"},
                )
            logger.info("[ReportAgent] Uploaded report to blob: %s/%s", settings.STORAGE_REPORTS_CONTAINER, blob_name)
        except Exception as exc:
            logger.error("[ReportAgent] Failed to upload report to blob: %s", exc)
